// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: Increment/Increment.proto

package Increment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncRequest) Reset() {
	*x = IncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_Increment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncRequest) ProtoMessage() {}

func (x *IncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_Increment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncRequest.ProtoReflect.Descriptor instead.
func (*IncRequest) Descriptor() ([]byte, []int) {
	return file_Increment_Increment_proto_rawDescGZIP(), []int{0}
}

type IncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Inc     int32 `protobuf:"varint,2,opt,name=inc,proto3" json:"inc,omitempty"`
}

func (x *IncResponse) Reset() {
	*x = IncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_Increment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncResponse) ProtoMessage() {}

func (x *IncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_Increment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncResponse.ProtoReflect.Descriptor instead.
func (*IncResponse) Descriptor() ([]byte, []int) {
	return file_Increment_Increment_proto_rawDescGZIP(), []int{1}
}

func (x *IncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IncResponse) GetInc() int32 {
	if x != nil {
		return x.Inc
	}
	return 0
}

var File_Increment_Increment_proto protoreflect.FileDescriptor

var file_Increment_Increment_proto_rawDesc = []byte{
	0x0a, 0x19, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x69, 0x6e, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x6e, 0x63, 0x32,
	0x4e, 0x0a, 0x10, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x15, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Increment_Increment_proto_rawDescOnce sync.Once
	file_Increment_Increment_proto_rawDescData = file_Increment_Increment_proto_rawDesc
)

func file_Increment_Increment_proto_rawDescGZIP() []byte {
	file_Increment_Increment_proto_rawDescOnce.Do(func() {
		file_Increment_Increment_proto_rawDescData = protoimpl.X.CompressGZIP(file_Increment_Increment_proto_rawDescData)
	})
	return file_Increment_Increment_proto_rawDescData
}

var file_Increment_Increment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Increment_Increment_proto_goTypes = []interface{}{
	(*IncRequest)(nil),  // 0: Increment.incRequest
	(*IncResponse)(nil), // 1: Increment.incResponse
}
var file_Increment_Increment_proto_depIdxs = []int32{
	0, // 0: Increment.IncrementService.Increment:input_type -> Increment.incRequest
	1, // 1: Increment.IncrementService.Increment:output_type -> Increment.incResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Increment_Increment_proto_init() }
func file_Increment_Increment_proto_init() {
	if File_Increment_Increment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Increment_Increment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_Increment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Increment_Increment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Increment_Increment_proto_goTypes,
		DependencyIndexes: file_Increment_Increment_proto_depIdxs,
		MessageInfos:      file_Increment_Increment_proto_msgTypes,
	}.Build()
	File_Increment_Increment_proto = out.File
	file_Increment_Increment_proto_rawDesc = nil
	file_Increment_Increment_proto_goTypes = nil
	file_Increment_Increment_proto_depIdxs = nil
}
